apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: account-service
commonLabels:
  app: account-service
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: account-service
    newName: account-service
    newTag: latest