---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service
          env:
            - name: JAEGER_HOST
              value: "simplest-agent.observability.svc.cluster.local"
            - name: JAEGER_PORT
              value: "6831"
          imagePullPolicy: Never #Is madatoy to use local docker image
          ports:
            - name: app-port
              containerPort: 5001
          startupProbe:
            httpGet:
              path: /health
              port: app-port
            failureThreshold: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: app-port
            initialDelaySeconds: 10
            periodSeconds: 30 
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: app-port
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 20
