apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: user-service
commonLabels:
  app: user-service
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: user-service
    newName: user-service
    newTag: 0.3.1